#!/bin/sh
/usr/bin/Rscript /repo/workhorse/scripts/R/lighthoof_main.R --Rscript /usr/bin/Rscript \
    -i . -o /output --datDir /repo/workhorse/dat \
    --platform=EPIC --manifest=B4 --minPval=0.02 \
    --autoDetect \
    --writeAuto \
    --parallel \
    --verbosity=4

#    --single \
#    --plotAuto \
#    --writeCall \
#    --writeSigs \
#    --cluster  \

# End of file
